before_script:
  - echo "before!!!\n"
  - echo $CI_PROJECT_DIR
  - pwd
  - make before


stages:
  - build
  - test
  - deploy
  
build:
  stage: build
  script:
    - echo "build!!!\n"
    - pwd
    - ls -l
    - make build
  
test:
  stage: test
  script:
    - echo "test!!!\n"
    - pwd
    - make test

deploy:
  stage: deploy
  script:
    - echo "deploy!!!!\n"
    - pwd
    - make deploy



after_script:
  - echo "after!!!\n"
  - echo $CI_PROJECT_DIR
  - pwd
  - make after
  